### ISSUE TITLE
Query on Dataloader

### ISSUE THREAD

**Issue by abhishekaich27** [Okery/PyTorch-Simple-MaskRCNN#13]
How do I use a dataloader for the generalized dataset? I see we require a custom batch iterator.

**Comment by lixiuyu-cumt** [comment]
> How do I use a dataloader for the generalized dataset? I see we require a custom batch iterator.

I want to use dataloder to load data as well,so ,have you solved this issue?

**Comment by Okery** [comment]
Since the model only support ```batch_size = 1```, I think there is no need to use a dataloader.
If you want to learn more about loading data, you may refer to my another repo: [YOLOv5-PyTorch](https://github.com/Okery/YOLOv5-PyTorch)
It contains many skills on how to load data faster, e.g. data_prefetcher, distributed dataloader, and DALI dataloader.
